version: '1'
services:
  web:
    image: udm/udm-backend:latest
    build:
      context: .
    command: yarn dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "10500:3000"
    environment:
      NODE_ENV: development
